---
title: "Demultiplexing and DADA2"
author: "Katherine Mueller"
date: "3/3/2021"
output: html_document
---

# Load Libraries
```{r}
library(readr)
library(fs)
library(dplyr)
library(tibble)
library(Biostrings)
```
# Set up Paths, Directories, and Shell Variables
```{r}
#Directories
data.dir = "/data/project_data/argonne_data"
output.dir = "/home/guest/scratch/Plastics"
demux.dir = file.path(output.dir, "demux")
if (dir_exists(demux.dir)) {dir_delete(demux.dir)}
dir_create(demux.dir)

#Files
map.file = file.path(data.dir, "200114_McCumber_16SFW_AS_200110_corrected_final.txt")
barcode.fastq = file.path(data.dir, "Undetermined_S0_L001_I1_001.fastq.gz")
r1.fastq = file.path(data.dir, "Undetermined_S0_L001_R1_001.fastq.gz")
r2.fastq = file.path(data.dir, "Undetermined_S0_L001_R2_001.fastq.gz")

#Set bash variables
Sys.setenv(MAP_FILE = map.file)
Sys.setenv(OUT_DIR = output.dir)
Sys.setenv(DEMUX_DIR = demux.dir)
Sys.setenv(RAW_FASTQ_DIR = data.dir)
Sys.setenv(BARCODE_FASTQ = barcode.fastq)
```

#Check Data Integrity
```{bash}
cd $RAW_FASTQ_DIR
md5sum -c md5_checksum_compressed_fastqs.txt
```
I can see that our metadata file is labeled as having been corrected from the original. Unfortunately, the md5 checksum appears to be searching for the original, so I don't know if we have a way of checking the integrity of the metadata file.
